### ISSUE TITLE
Enhancement - omnidb server listen on localhost only

### ISSUE THREAD

**Issue by rotten** [OmniDB/OmniDB#195]
Although you can change the ports, when omnidb-server starts up, it listens on 0.0.0.0, and it isn't obvious that can be easily changed to just listen on localhost, or a specific private IP address (for multi-homed systems).

-h is already used for "help".

You could optionally parse the port options to include a listening hostname like this:
`omnidb-server -p localhost:55555 -w localhost:55000
`

**Comment by rafaelthca** [comment]
Hi Rotten,

that is a great suggestion. OmniDB server actually listens to all IP's related to the machine where the server was started:

127.0.0.1, local network IP, public internet IP.

Having a parameter to specify which IP to listen to is a great idea since it gives the user the possibility to block access from undesired locations, hence enhancing security.

This parameter will be included in the next release, as the materialized views and foreign tables.

**Comment by wind39** [comment]
Hi @rotten ,

Thanks very much for your feedback. Recent version of `omnidb-server` allows you to specify listen address and ports. Please refer to `omnidb-server -h`:

```text
Usage: omnidb-server [options]

Options:
  --version             show program's version number and exit
  -h, --help            show this help message and exit
  -p PORT, --port=PORT  listening port
  -w WSPORT, --wsport=WSPORT
                        websocket port
  -H HOST, --host=HOST  listening address
  -c CONF, --configfile=CONF
                        configuration file
```

I'm closing this issue now.
