### ISSUE TITLE
Elaborate on degree of DBMS support

### ISSUE THREAD

**Issue by mikini** [OmniDB/OmniDB#296]
I apologize for maybe having been daft and in a hurry when discovering your nice looking tool. But the yellow tool icons in the [Support Status](https://omnidb.org/en/#Overview-2) on the homepage front page didn't clearly indicate to me the status of the DBMS support. I had to dig into the code to notice that my target database (firebird) is not fully supported at the moment by OmniDB. 

I see [firebird code in Spartacus](https://github.com/OmniDB/OmniDB/blob/9c9fa9a930783d38ddd559707c9b6abc95bbeea6/OmniDB/OmniDB_app/include/Spartacus/Database.py#L1594) but it is not obvious to me if and how that is reflected into the functionalities of OmdiDB and I see no mention in [the documentation](https://github.com/OmniDB/doc/search?q=firebird+OR+support&type=Code&utf8=%E2%9C%93) of the details.

Could you please elaborate on this?

**Comment by wind39** [comment]
Hi @mikini ,

Thanks for your input. I will try to explain here.

When we first released OmniDB, it was written in C# and ASP.NET. It was built on top of the C# version of Spartacus [1], and because of that it provided basic DBMS support for the following RDBMS systems:

- **Firebird**: tables (PK, FK, uniques, indexes, data) and procedures
- **MariaDB / MySQL**: tables (PK, FK, uniques, indexes, data), functions and procedures
- **Microsoft Access**: tables (PK, FK, uniques, indexes, data)
- **Microsoft SQL Server / Compact Edition**: tables (PK, FK, uniques, indexes, data)
- **Oracle**: tables (PK, FK, uniques, indexes, data), functions and procedures
- **PostgreSQL**: tables (PK, FK, uniques, indexes, data) and functions
- **SQLite**: tables (PK, FK, uniques, indexes, data)

Spartacus is a database connection wrapper, which exposes common DB API methods into a single, generic and lean API. The OmniDatabase is a library that extends Spartacus functionality by adding meta-data queries, templates and other stuff used by OmniDB. For more details on the OmniDatabase C# version, as well as what was supported for each RDBMS, please check [2].

OmniDB ASP.NET / C# version also provided a database/schema conversion tool, which was capable of converting tables and its structures. The source code of Spartacus C# and the whole OmniDB C# version (which can be found here [3]) are not maintained anymore.

When we decided to re-write OmniDB into Django / Python, I first re-wrote the whole Spartacus library into a brand new, much simpler, leaner and faster Python library [4]. I also dropped support to MS Access and SQLCE, as they are Windows-only, and included support to IBM DB. So, as Spartacus is the backbone that allows OmniDB to connect to multiple RDMBS systems in a generic way, I can say that this is already full translated into Python, and that's why we consider that OmniDB support to the RDBMS systems with the yellow tool icons is in progress.

Another important decision we made is to support the whole set of features PostgreSQL has to offer, before including support to another RDBMS system. The tool has grown and matured a lot in the Python version, so I invite you to try the tool in the C# version (for Firebird and all other RDBMS systems it supports, if you might) and then the Python version (for PostgreSQL only atm). We also wrote some articles showing how OmniDB integrates into many important extensions and features of PostgreSQL here [5].

We believe in a few months we will have finished full support for PostgreSQL. Also the OmniDB interface will have many exciting improvements and new features by there. Then we will add support to the other RDBMS again, but now in Python version. As you can see, Spartacus is already full translated into Python, so we will need to translate OmniDatabase and adapt other parts of the OmniDB interface to allow the new RDBMS systems in the Python version. Longer term, the OmniConversion feature will also be translated into Python. Stay tuned!

[1] https://github.com/wind39/spartacus-csharp
[2] https://github.com/OmniDB/OmniDB/tree/csharp/OmniDatabase
[3] https://github.com/OmniDB/OmniDB/tree/csharp
[4] https://github.com/wind39/spartacus
[5] https://blog.2ndquadrant.com/omnidb/

**Comment by wind39** [comment]
Hi @mikini ,

Just a quick update. Two months ago we released 2.6.0 with Oracle support, and now we just released 2.7.0 with MySQL / MariaDB support. Firebird is on the roadmap, coming soon.

Regards,
William

**Comment by wmertens** [comment]
@wind39 I'm interested in SQLite support, but I can't find how to enable it.

**Comment by wind39** [comment]
Hi @wmertens ,

SQLite support is not implemented yet in OmniDB 2.x. We plan to implement SQLite support soon.

Regards,

William

**Comment by wind39** [comment]
Hi,

Closing this for now.

Support for other databases such as Firebird and SQLite is coming out soon. Please stay tuned to the release announcements and release notes.

Best regards,

William
