### ISSUE TITLE
Enhancement - xlsx as datasource + field adapters

### ISSUE THREAD

**Issue by twheelmaker** [OmniDB/OmniDB#30]
I know this is not vendor neutral and potentially ugly (jet ado driver required... registry hack to be able to read cells with more than 255 characters), but in practice (aka reality), having the ability to use a xlsx spreadsheet as a datasource and import data rows into a db table based on some kind of user-defined mapping is something that would put this tool into the 'must-have' category. Also ugly is there is no concept of schema in a spreadsheet so may not be in scope, but this is a pain point for anyone who's ever had to do it.

Triple ugly-bonus (not limited to just xlsx import)... maybe a "field adapter" override virtual method that offered a programmatic slice of execution context for 'massaging' data prior to committing the row in target table (maybe with the current row in context?)! Might not be feasible if you're only using ddl and no c# during that step... ehh.

In any case, keep up the good work!

**Comment by wind39** [comment]
Hi, @twheelmaker, thank you for your suggestion!

I just created issue #31 to address your "xlsx as datasource" request. We've received many other request like this, regarding to data import from xlsx, csv and even dbf files.

We want to make such a great feature available not for Windows users, but for users hosting OmniDB on other operating systems. That's why Windows-only drivers are not an option. If by any chance you know about another driver for XLSX (JDBC, maybe? If it's JDBC we can try to make it work using IKVM bridge), please let me know.

I started playing with a way to (regardless the operating system) execute SQL statements against CSV files, and I want to extend that to XLSX and DBF files too. It's called **PollyDB** and it's part of [Spartacus](https://github.com/wind39/spartacus). Spartacus is used as a "ADO wrapper" by OmniDB. It's still pretty rudimentary, strongly needs some optimizations, and currently supporting only a very small subset of SQL: *select*, *from*, *full join*, *inner join* and a limited *where*. But, with a lot of effort, it may become a way to make that happen.

Now about your "field adapter" request... You mean execute a custom function on some columns of a table in database A, before converting it to database B? It's a great suggestion, we are going to investigate about that in issue #32.

Thanks again!

**Comment by twheelmaker** [comment]
wow, thanks for the quick reply.

windows only jet driver is the only way I know of to reliably interact with ms xlsx files like a db, but a properly escaped csv option would probably work fine.

field adapter in my mind would expose an interface or abstract extendable class with override events like OnBeforeFieldAssign(datarow r)... the interface would look something like

IFieldAdapter {
guid importJobId;
string sourceColumn;
string destColumn;
object value;
Type thisdestColumnType;

OnBeforeFieldAssign(datarow r){
// do some stuff / logic on datarow r... maybe a lookup elseware or other type of 'massaging of the data'
value = (thisdestColumnType)"some derived value based on my logic";
}
}

you'd be able to create any number of field adapters registered to a specific job, BUT... this would require a compilation of source or... if you want to keep it nice for the end user... a live recompilation based on cs files dropped into a field adapter folder. I've built hot swappable 'plugin' systems like this using csscript http://www.csscript.net/index.html and mono. csscript provides an 'AlignToInterface' method that recompiles text as c# on the fly. the other option is to host some kind of interpreter like a js v8 engine, but the fieldadapter would need to be written in js and the whole interface idea goes out the window. i havn't dug into your code, but if you're in too deep with ddl, the fieldadapter logic might be doable in a user defined function in sql that could be invoked, but i don;t think this is consistent across dbs.

again this gets ugly and maybe out of scope, but it would be a killer feature.

**Comment by wind39** [comment]
Thanks again, @twheelmaker.

CS-Script looks neat, I'll check it out. A plugin system for user defined functions is a splendid idea. We'll surely spend some time on this and I'll let you know about any news.

**Comment by smartmeter** [comment]
I am interested in it too

**Comment by wind39** [comment]
This issue does not make much sense at the moment, since OmniDB was converted into Python and currently there is no OmniConvert yet. We plan to implement such feature, but not in the foreseeable future.
