### ISSUE TITLE
omindb.contexts does not exist at debug function.

### ISSUE THREAD

**Issue by edmundorobles** [OmniDB/OmniDB#321]
I tried to debug a function but I got the following message:
_relation "omnidb.contexts" does not exist
LINE 1: delete from omnidb.contexts t where t.pid not in (select pid..._

I have postgresql 10.

**Comment by rafaelthca** [comment]
Hi edmundorobles,

OmniDB requires a special schema to debug the functions. Additionally, the database must contain omnidb_plugin, a library that enables us to control the function flow while it is executing.

You received this error because the the schema omnidb with the control tables weren't created. Please follow the doc and the plugin instructions to create the schema and install the plugin:

https://omnidb.org/en/documentation-en/13-debug-plpgsql-functions-en
https://github.com/OmniDB/OmniDB/tree/master/omnidb_plugin

What OS is hosting your postgresql 10? The plugin currently works only on databases hosted in Linux. We are working to add support to Windows. But OmniDB can be executed from any OS that you can still debug the functions.

Rafael.

**Comment by wind39** [comment]
Closing this, as we didn't get any response from @edmundorobles .

@edmundorobles , please feel free to open a new issue.
