### ISSUE TITLE
Autocomplete doesn't work 

### ISSUE THREAD

**Issue by SIGISLV** [OmniDB/OmniDB#383]
Hi,
First thank you for all of this good work. I'm struggling with the shortcut CTRL SPACE doesn't work in my case. I have installed the last version (2.5) in 64bit on windows.

**Comment by rafaelthca** [comment]
Hi SIGISLV,

Thank you for reaching us. I have just tested and it seems to be working in my environment, windows 7 64 bits, OmniDB-app.

Can you tell us how you are trying to use the autocomplete? Currently it works only for columns in tables and subqueries. In order to trigger the autocomplete the editor cursor must be right after the alias of the query/subcolumn, here is an example:

`
select tab(cursor is here)
from table_1 tab
`

There is an issue to expand autocomplete to other elements that may appear in a query, so we will improve autocomplete in next releases.

Rafael.

**Comment by SIGISLV** [comment]
I had try autocomplete on table of a schema. Which is not possible on current version. I am looking forward on this feature on the next release. Thank you for the answer and your work.
