### ISSUE TITLE
Mistake copying row with a field boolean type

### ISSUE THREAD

**Issue by erdusa** [OmniDB/OmniDB#392]
When I copy a row that it has a field boolean type, and this is null, and then I paste this row, OmniDB tries inserting a empty character in the boolean field

**Comment by wind39** [comment]
Hi @erdusa ,

Thanks for reporting this. We could simulate the behavior you described. This happens because PostgreSQL `boolean` datatype is being considered a `text` datatype erroneously inside of OmniDB.

The fix for this will be packaged for the next release. We will keep this issue open until then.

Regards,
William

**Comment by wind39** [comment]
Hi @erdusa ,

This issue was fixed in version 2.6.0 we just released. Can you please try? We wait your feedback, so this issue is open for now. Thanks.

Regards,
William Ivanski

**Comment by erdusa** [comment]
Hi @wind39, 

I can see that this issue is resolved.
Thanks, Have a nice day

Sincerely
Eudis Rene Duarte

**Comment by wind39** [comment]
Thanks, closing :+1:
