### ISSUE TITLE
omnidb-server: Running On Ubuntu As a Service

### ISSUE THREAD

**Issue by jday-gis** [OmniDB/OmniDB#548]
Has anyone setup omnidb-server on Ubuntu to run automatically as a service.

If so, would you mind posting the steps you performed to make that happen ?

**Comment by monnierpascal** [comment]
Hello, did you find a solution ?

I've create a .service file but I have the following error

 _Loaded: loaded (/etc/systemd/system/omnidb.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since jeu. 2018-06-21 18:36:26 CEST; 11s ago
  Process: 576 ExecStart=/home/ncitl/omnidb-server (code=exited, status=203/EXEC)
 Main PID: 576 (code=exited, status=203/EXEC)_

Here is the content of my omnidb.service file

```
[Unit]
Description=omnidb Service
After=network.target

[Service]
User=ncitl
Group=ncitl
WorkingDirectory=/home/ncitl/
Environment="PATH=/home/ncitl"
ExecStart=/home/ncitl/omnidb-server
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```


`sudo systemctl start omnidb` : ok no error

`sudo systemctl status omnidb` show me the error above.

**Comment by monnierpascal** [comment]
Ok I found a solution with link

https://stackoverflow.com/questions/19233529/run-bash-script-as-daemon

**Comment by barthisrael** [comment]
Hello, sorry for the delay :(

You could do something like this:

`vim /lib/systemd/system/omnidb-server.service`

Fill it with:

```
[Unit]
Description=OmniDB: executes omnidb-server.

[Service]
Type=forking
ExecStart=/bin/bash -c "omnidb-server &"
RemainAfterExit=yes
User=root
Group=root
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=omnidb-server

[Install]
WantedBy=multi-user.target
```

**Type=forking** will make it possible to use systemctl start and stop statements.

`ln -s /lib/systemd/system/omnidb-server.service /etc/systemd/system/omnidb-server.service`

`systemctl daemon-reload`

And, to add output to rsyslog and save it to file /var/log/omnidb-server.log:

`vim /etc/rsyslog.d/omnidb-server.conf`

Content:

```
if $programname == 'omnidb-server' then /var/log/omnidb-server.log
if $programname == 'omnidb-server' then ~
```

`systemctl restart rsyslog`

`systemctl start omnidb-server`

**Comment by wind39** [comment]
`omnidb-server` Linux packages could provide the files mentioned by @barthisrael .

**Comment by wind39** [comment]
Hi @jday-gis , @monnierpascal ,

OmniDB 2.11 was released a few days ago. The server packages now install a service in `systemctl`. Can you please test it and provide your valuable feedback?

Thanks in advance,

William Ivanski

**Comment by wind39** [comment]
Closing it now.
