### ISSUE TITLE
Suggestion: return of queries

### ISSUE THREAD

**Issue by pasquall** [OmniDB/OmniDB#571]
When we run a DELETE or UPDATE or INSERT it is very important to see its output, but OmniDB just shows "Done."

Example on PostgreSQL (psql):
# insert into some_table (id, user, data) values (636, 53, 'some data');
INSERT 0 1

Or:
# update some_table set data = 'something else' where id = 636;
UPDATE 1

Or:
# delete from some_table where id = 636;
DELETE 1

Is it possible to change this behavior in the future?

Thanks

**Comment by rafaelthca** [comment]
Hi @pasquall,

that feature has been requested before, we will increase priority since a lot of people want it. For now you can use the console tab to perform such operations, you can see the more detailed output there:

![image](https://user-images.githubusercontent.com/9335851/41234577-93bb5298-6d5a-11e8-85a6-56411be7b446.png)

Thanks for reporting.

Rafael.

**Comment by wind39** [comment]
Hi @pasquall ,

In OmniDB 2.12.0 we improved the Query Tab to show the number of changed rows (inserted, updated or deleted) instead of simply "Done".

We released OmniDB 2.14.0 last week. Please try it and provide your valuable feedback, as always.

Best regards,

William

**Comment by wind39** [comment]
Closing this.
