### ISSUE TITLE
Using OmniDB on AWS Cloud9

### ISSUE THREAD

**Issue by pankajbsn** [OmniDB/OmniDB#596]
I was trying to use OmniDB on AWS Cloud9. OmniDB-server could be an ideal fit for AWS Cloud9. The installation and start of the server went fine. But then, in the browser app I get the error that it is not able to connect to Webserver on port 25482. This is most probably because on AWS Cloud9, apps can only be connected to if they were running on port 8080. I changed the web server to run on port 8080. Now I dont have another port to give to websocket server.
My question is: What is the role of websocket server & is it possible to run OmniDB server without Websocket server?

**Comment by rafaelthca** [comment]
hi @pankajbsn,

OmniDB uses the websocket server to serve features that require bi-directional communication. This is because OmniDB allows users to perform as many operations as he wants in parallel.

The features that use the websocket server:

- Query Tab
- Console Tab
- PLpgSQL debugger
- Edit data tab
- Data mining

Currently the only way to host OmniDB in the cloud and use the same port for both the app and websocket servers is by using a reverse proxy such as Nginx, this page in the docs explains how to do that:

https://omnidb.org/en/documentation-en/19-deploying-omnidb-server

**Comment by wind39** [comment]
Hi @pankajbsn ,

Just checking if @rafaelthca 's suggestions were useful to help you host OmniDB server in AWS Cloud9.

Regards,

William Ivanski

**Comment by pankajbsn** [comment]
Yes. It helped. Thanks a lot.
