### ISSUE TITLE
Notes on using Omni to convert sqlserver to postgresql

### ISSUE THREAD

**Issue by mason-bially** [OmniDB/OmniDB#64]
I recently did a migration from sqlserver to postgresql, I made a number of changes to improve the process. I have documented them in the following database script. I would happily work to contribute these changes if I knew how (the project doesn't seem to have a contributions guideline). I'm not sure how much work would be required to support these changes for all databases, and some of them are opinionated, half finished, and honestly I'm not entirely sure what other consequences they will have.

#### Omniconversion/Program.cs

On line 384 I added the following condition. For some reason it read my sqlserver `varchar(MAX)` as `-1` and in postgresql that most closely maps to `varying character`; where as `varying character(-1)` was an error.

```csharp
+     || v_length == "-1"
```

Inserted as line 414 and 415 I added the following branch to encode and decode bytes as hex correctly.

```csharp
+    else if (v_category == "bytes")
+        v_insert_command.AddParameter(v_columns.Rows[i]["column_name"].ToString().ToLower(), Spartacus.Database.Type.QUOTEDSTRING, v_representatives.Rows[v_rep_index]["dt_st_writeformat"].ToString());
```

#### tool_database

```
update representatives
set rep_st_default='integer', dt_type='integer'
where dbt_st_name='postgresql' and cat_st_name='integer'

INSERT INTO data_categories
    values ('uid', 'Unique Identifier', 'other');
    
INSERT INTO data_categories
    values ('bytes', 'Byte Data', 'other');

INSERT INTO data_categories
    values ('xml', 'Xml Data', 'text');
    
insert into data_types
values ('xml', 'sqlserver', 'xml', 0, '''#''', '#', '#');

insert into data_types
values ('xml', 'postgresql', 'xml', 0, '''#''', '#', '#');

insert into representatives
values ('xml', 'postgresql', 'xml', 'xml');

insert into representatives
values ('xml', 'sqlserver', 'xml', 'xml');


insert into data_types
values ('uid', 'sqlserver', 'uniqueidentifier', 0, '''#''', '#', '#');

insert into data_types
values ('uid', 'postgresql', 'uuid', 0, '''#''', '#', '#');

insert into representatives
values ('uid', 'sqlserver', 'uniqueidentifier', 'uniqueidentifier');

insert into representatives
values ('uid', 'postgresql', 'uuid', 'uuid');


update data_types
set cat_st_name='bytes', dt_st_readformat='CONVERT(varchar(MAX),#,2) as #'
where dbt_st_name='sqlserver' and (dt_type='varbinary' or dt_type='binary');

insert into data_types
values ('bytes', 'postgresql', 'bytea', 0, 'decode(''#'', ''hex'')', '#', '#');

insert into representatives
values ('bytes', 'sqlserver', 'varbinary(MAX)', 'varbinary');

insert into representatives
values ('bytes', 'postgresql', 'bytea', 'bytea');
```

Byte Data often doesn't appear correctly and would probably need a lot more work to clean up.

**Comment by wind39** [comment]
We are glad you were able to migrate from SQL Server to PostgreSQL. Thank you for this issue, it really has valuable information.

We weren't aware that one could do `varchar(MAX)` in SQL Server, that's why OmniDB misunderstood this as -1. I'll search if other RDBMS systems allow a similar syntax, but your solution seems fine 'cause this cases will default to `string` representative on the target RDBMS.

I see you updated the `integer` representative of PostgreSQL to `integer`. We let it as `bigint` because of a massive migration we did from Oracle to PostgreSQL, and `integer` on Oracle is larger than `integer` on PostgreSQL. But you are right, it needs to be `integer`, because `bigint` occupies much more space and on most of the cases `integer` does fine.

Your suggestions of including `uid`, `bytes` and `xml` categories are most welcome. We'll include that on our default **tool_database**. Please note that we were aware of those categories and the fact that the user can include or alter them on **tool_database** is a feature we planned. But for now there is no documentation explaining how to understand **tool_database**. We'll write this documentation in the near future.

You mentioned that you don’t know how much work would be required to extend these changes to other databases. So, to clarify that, the only requirement for the conversions to work properly is that every DBMS **must** have one representative for each category to map source and target data types even if the DBMS doesn’t support that category. For instance, SQLite’s representative for the Date category is “Text”, so all dates will be converted as text.

Since you created 3 new categories, the table **representatives** must be populated with 3 * 9 = 27 new records (given that we currently support 9 DBMS).

In my analysis, all your suggestions can be pushed to main repository. We are sorry we still doesn't provide *Contributing Guidelines*, we'll write this ASAP. In the meantime, would you be kind to make a PR with your alterations on **OmniConversion/Program.cs** and **tool_database**? This way your contributions will be counted on this repo. But if you prefer, I can make this alterations, no problem.

**Comment by mason-bially** [comment]
If you don't mind my lethargy (holidays, and this is a low priority item for me (I only needed to do the conversion once; however I am more than happy to contribute to open source technologies - time permitting)), I would be happy to contribute the changes through a pull request. I'm not an expert in database technologies, even the *postgres* and *sqlserver* information I know I learned on the fly (and I didn't plan on learning much more than I already know). Part of the reason I would prefer someone more knowledgeable in the technologies to at least double check my work. For example, I'm not entirely convinced I was right to change the default *postgres* representation to `integer`. In many respects *postgres* seems designed to use `bigint`s for primary keys (the sequences feature for example is typed to `bigint`s, how the source code reading the database was expecting `integer`s so I just went with it).

I'd be willing to make a first draft of the specs of the `tool_database` - it may be helpful if an outsider wrote it - in my experience an outside perspective of hitherto undocumented technical specifications is often illuminating. Although it probably wouldn't be done for a week at best.

As for the new data types, the `bytes` data type is perhaps the one in need of the most work and perhaps even extra code. I later noticed the above patch to forward the write string to Spartacus doesn't seem to work. If someone would be willing to make the relevant changes to that library so the change I made (or an equivalent - more consistent - change) can actually use the write string correctly. As it is I had to apply a post-conversion fixup my database that I had correctly placed in the `tool_database`. As it is I am transmitting `bytes` a string of hex. The `xml` and `uuid` datatypes falling back to text seems quite reasonable.

All-in-all Omni DB was a breeze to use, thanks for building such a great tool. I'd be happy to contribute a couple of things to the conversion feature to aid the pain-points I experienced in using it over the next few months.

**Comment by mason-bially** [comment]
The reason I had the third argument is, as I mentioned, to get the write format to run on bytes, this line of the sql might make it more clear:

```
insert into data_types
values ('bytes', 'postgresql', 'bytea', 0, 'decode(''#'', ''hex'')', '#', '#');
```

I only had a megabyte of data per row and it seemed to go perfectly fine as hex text. I tried undefined and it instead turned the C# `System.Byte[]` into that text string and put the binary of that string into the database. Not what I was looking for.

**Comment by wind39** [comment]
Thank you for the information, I'll investigate that.

**Comment by RickZeeland** [comment]
Here is the source code in C# for a SQL Server to PostgreSQL converter: [https://www.codeproject.com/Tips/1068276/Convert-SQL-Server-Database-to-PostgreSQL](url)
Enjoy !

**Comment by wind39** [comment]
Unfortunately the C# OmniConvert is not supported anymore. We plan to port that into the OmniDB Python version. Closing this issue for now.
