### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by MichaelDBA** [OmniDB/OmniDB#876]
Nothing appears in the omnidb log folder, so here is me copying what I see on the screen as omnidb is starting up.

Starting OmniDB...
Starting OmniDB websocket...
Checking port availability...
Starting websocket server at port 25482.
Starting OmniDB server...
Checking port availability...
Starting server OmniDB 1.14.0 at 0.0.0.0:8000.
Starting migration of user database from version 2.9.0 to version 2.10.0...
OmniDB migration error: Error migrating from version 2.9.0 to version 2.10.0: UNIQUE constraint failed:
mon_units.unit_id
Opening OnmiDB...

Window opens with --> Server Error (500)

**Comment by rafaelthca** [comment]
Thanks for reporting.

What OS? Can you point us to the package/installer you used?

Regards,

Rafael.

**Comment by MichaelDBA** [comment]
Windows 10 Home edition.  Downloaded from Omnidb web site:
https://omnidb.org/dist/2.14.0/omnidb-app_2.14.0-windows-amd64.exe

**Comment by wind39** [comment]
Hi @MichaelDBA ,

Thank you very much for reporting this issue and for the details you provided. We managed to reproduce this issue here.

I wrote a fix for your issue here: https://gist.github.com/wind39/2bcb1250834fce1416af5bdec277bed5

Please locate file `.omnidb/omnidb-app/omnidb.db` folder inside your home user folder. This is the OmniDB user database, a SQLite database. You need to run the fix above into this SQLite database in order to get your OmniDB running again.

On Linux and MacOSX, provided that you have downloaded file `omnidb_fix.sql` from the gist above into the folder `.omnidb/omnidb-app/omnidb.db`, you can run the following command to apply the fix:

```
sqlite3 omnidb.db < omnidb_fix.sql
```

On Windows, the executable will be probably named `sqlite.exe`. If you don't have SQLite installed, please check here: https://sqlite.org/index.html

Then open your OmniDB 2.14 again, it shouldn't give such error anymore, and you will be able to use 2.14 with all your charts you have created in 2.9.

Please let us know how this goes.

Best regards,

William

**Comment by MichaelDBA** [comment]
Thank you so much.  The fix above solved the problem.  Here is the sqlite binary executable that I had to download to run the command for Windows:
https://sqlite.org/2019/sqlite-tools-win32-x86-3270200.zip

The new version, 2.14.0 is working fine now.  Again, thanks for your swift fix!
