### ISSUE TITLE
password in connection string not used

### ISSUE THREAD

**Issue by ccurvey** [OmniDB/OmniDB#938]
When executing a query, OmniDB asks for a password, even though I have defined one in my connection string (e.g. postgresql://user:pass@host:port/db)

I'm not sure if I can use a .pgpass file in this case, as my browser is running on a Chromebook, and I'm using OmniDB in server mode.

**Comment by wind39** [comment]
Hi @ccurvey ,

That's correct, we just verified that, due to an oversight, unfortunately last release 2.15 broke proper handling of connection strings. If you test 2.14 (when connection strings were introduced), you will see that the password is properly handled.

The `.pgpass` file should be placed in the home folder of the user who is running `omnidb-server`,  as the connection is made from the `omnidb-server`. Not sure if it would be possible in your installation, though.

What was the OmniDB package you installed? As an alternative, I can compile a package fixing this issue for you if you like.

Best regards,

William

**Comment by wind39** [comment]
Hi @ccurvey ,

I fixed this, the fix is going out on next OmniDB release. I will keep this open to notify you here when the next release comes out, and then we will be waiting on your feedback.

Regards,

William

**Comment by wind39** [comment]
Hi @ccurvey ,

Today we released OmniDB 2.16.0 with this fix. Would you please try it out and give us your valuable feedback, as always?

Keeping this issue open for a few more days.

Regards,

William

**Comment by ccurvey** [comment]
Perfect!  Thanks very much for the fix!

**Comment by a-salimkhanov** [comment]
Hi

Connection using a "connection string" still requests password even if password included, like...
mysql://user.pass(@host:port

OmniDB 2.17.0
Linux Mint 20 (Cinnamon 64-bit) | 5.4.0-48-generic #52-Ubuntu SMP

Thank you,
