### ISSUE TITLE
New User cannot login

### ISSUE THREAD

**Issue by RabbidDog** [OmniDB/OmniDB#951]
v2.15.0
System: Docker
Running a docker container where omniDB was installed from a zip. No extra configuration files were included

in entrypoint.sh I have the following lines

`
python3 /opt/OmniDB-${OMNIDB_VERSION}/OmniDB/omnidb-config.py --createuser $USERNAME $PASSWORD --dropuser **admin**
python3 /opt/OmniDB-${OMNIDB_VERSION}/OmniDB/omnidb-config.py --listusers

python3 /opt/OmniDB-${OMNIDB_VERSION}/OmniDB/omnidb-server.py --host=0.0.0.0 --port=8080 -d /etc/omnidb`

### expected: 
- **admin** user should not exist and cannot login
- user $USERNAME should exist in the list of users
- user $USERNAME can login using $PASSWORD

### found:
- **admin** user **does not** exist in the list of users but can still login
- user $USERNAME exist in the output of listusers
- user $USERNAME **can't login** using $PASSWORD

**Comment by rafaelthca** [comment]
Hi @RabbidDog,

Thanks for opening this. The problem is that, when you use OmniDB from source (without installing a package), `omnidb-config.py` was pointing to the database file contained in OmniDB's directory, this is for development mode.

`omnidb-server.py` is used only after deployment so it is pointing to the correct database file. So your problem is that config is changing a file that is not being used by the app itself.

I just pushed a change to the master branch:

https://github.com/OmniDB/OmniDB/blob/master/OmniDB/OmniDB/custom_settings.py

The only change was setting `DEV_MODE = False`. Feel free to download the master branch again or change that line manually in your code.

Now, `omnidb-config.py` should point to the correct location. You can also specify the location of database file with option `-d` (after setting DEV_MODE to false). If you don't specify, it will use the default location (`~/.omnidb/omnidb-server/`)

Let me know if that works.

Rafael.

**Comment by RabbidDog** [comment]
Thx for your response

Unfortunately this is what I see now

`Creating user...
Error:
no such table: users`

this is my current setup
- I downloaded the master branch, so ` DEV_MODE = False` is set
- I tried all combinations of using default database file location or using the -d options, but the resulting error is the same. I even passed -d to omnidb-config.py but same error.

Am I missing something.
Note that I am running the omnidb-config.py before I start the server with omnidb-server.py .

**Comment by rafaelthca** [comment]
You need to start the server for the first time, so the folder with database and log files are created. This is missing in the docs, specially for users who are not using the packages, apologies for that. We'll improve this for the next release.
